name: feature-tracking-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - scipy
  - numpy
  - xarray
  - metpy
  - scikit-image
  - netcdf4
  - matplotlib
  - pandas
  - cartopy
  - geopandas
