name: feature-tracking-dev
channels:
  - conda-forge
dependencies:
  - python >= 3.13
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - scipy
  - numpy
  - xarray
  - metpy
  - scikit-image
  - netcdf4
  - matplotlib
  - pandas
  - cartopy
  - geopandas
  - s3fs
  - zarr
  - pip
  - pip:
    - pelicanfs